### ISSUE TITLE
Exiting Cygwin in GHA

### ISSUE THREAD

**Issue by brianpham** [cygwin/cygwin-install-action#1]
Is there a way to exit from cygwin? Seems like once I am in it, I am not able to log out of it.

**Comment by jon-turney** [comment]
Your question doesn't say what you are trying to achieve and what you've tried, so I can only offer guesses to help you, but:

* Each job.<job_id>.steps.run starts an independent process. Provided you're not setting jobs.<job_id>.defaults.run.shell, a separate step should execute using the default shell (pwsh).
* If you're explicitly running a Cygwin shell in your step, then you should be able to craft a multi-line command which executes commands after that shell has exited.

**Comment by jon-turney** [comment]
Closing as no response
