### ISSUE TITLE
cygwin install action doesn't make a github cache

### ISSUE THREAD

**Issue by spk121** [cygwin/cygwin-install-action#10]
I notice that when I use the cygwin install action, I don't see a cache file getting created.  I believe this means that every time I run my CI/CD, it is downloading a fresh set of files from Cygwin or one of its mirrors.

There's nothing wrong with that, of course, but, if cygwin is worried about bandwidth usage, you could add some download caching like how the msys2/setup-msys2@v2 action does.

Sorry, but, I don't understand it well enough to offer a patch.

**Comment by me-and** [comment]
Yes, it's definitely the case that this action currently downloads packages every time. I've been working on adding caching – see #6 – but that work has been stalled for some time, as a variety of personal life issues mean I've not been able to put much time into OSS projects for a while.

I'm planning on picking that work up as soon as I can (it's mid-way down my OSS to-do list), but I don't have any estimate for that. Alternatively, I'd be entirely happy for someone else to take that work and run with it.

**Comment by spk121** [comment]
Duplicate of #6
